### ISSUE TITLE
Tutorial damBreak not working 

### ISSUE THREAD

**Issue by Gitzzly** [STFS-TUDa/blastAMR#1]
Hey, 

when trying to run the tutorial damBreak2D case I get the following problem executing updateMesh. FOAM_CODE_TEMPLATES is set to ../../etc/codeTemplates/dynamicCode, since I'm running the ./Allrun script.

`
    /*---------------------------------------------------------------------------*\
    | =========                 |                                                 |
    | \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
    |  \\    /   O peration     | Version:  v2012                                 |
    |   \\  /    A nd           | Website:  www.openfoam.com                      |
    |    \\/     M anipulation  |                                                 |
    \*---------------------------------------------------------------------------*/
    Build  : 79e353b84e-20201222 OPENFOAM=2012
    Arch   : "LSB;label=32;scalar=64"
    Exec   : updateMesh
    Date   : Nov 09 2023
    Time   : 09:52:45
    Host   : gitzzly
    PID    : 97486
    I/O    : uncollated
    Case   : /home/gitzzly/OpenFOAM/gitzzly-v2012/blastAMR/tutorials/damBreak2D
    nProcs : 1
    trapFpe: Floating point exception trapping enabled (FOAM_SIGFPE).
    fileModificationChecking : Monitoring run-time modified files using timeStampMaster (fileModificationSkew 5, maxFileModificationPolls 20)
    allowSystemOperations : Allowing user-supplied system call operations
    
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
    Create time
    
    Create mesh for time = 0
    
    Selecting dynamicFvMesh adaptiveFvMesh
    Selecting errorEstimator: coded
    Using dynamicCode for codedErrorEstimator emulateDelta at line 17 in "/home/gitzzly/OpenFOAM/gitzzly-v2012/blastAMR/tutorials/damBreak2D/constant/dynamicMeshDict"
    Could not load "/home/gitzzly/OpenFOAM/gitzzly-v2012/blastAMR/tutorials/damBreak2D/dynamicCode/platforms/linux64GccDPInt32Opt/lib/libemulateDelta_886cd9bdcbf9de5b2d10c8aaa6ee9241d41e170c.so"
    /home/gitzzly/OpenFOAM/gitzzly-v2012/blastAMR/tutorials/damBreak2D/dynamicCode/platforms/linux64GccDPInt32Opt/lib/libemulateDelta_886cd9bdcbf9de5b2d10c8aaa6ee9241d41e170c.so: cannot open shared object file: No such file or directory
    Invoking wmake libso /home/gitzzly/OpenFOAM/gitzzly-v2012/blastAMR/tutorials/damBreak2D/dynamicCode/emulateDelta
    wmake libso /home/gitzzly/OpenFOAM/gitzzly-v2012/blastAMR/tutorials/damBreak2D/dynamicCode/emulateDelta
        Ctoo: codedErrorEstimatorTemplate.C
    In file included from codedErrorEstimatorTemplate.C:29:
    codedErrorEstimatorTemplate.H:38:10: fatal error: errorEstimator.H: No such file or directory
       38 | #include "errorEstimator.H"
          |          ^~~~~~~~~~~~~~~~~~
    compilation terminated.
    make: *** [/home/gitzzly/OpenFOAM/OpenFOAM-v2012/wmake/rules/General/transform:35: Make/linux64GccDPInt32Opt/codedErrorEstimatorTemplate.o] Error 1
    
    
    --> FOAM FATAL IO ERROR: (openfoam-2012)
    Failed wmake "dynamicCode/emulateDelta/platforms/linux64GccDPInt32Opt/lib/libemulateDelta_886cd9bdcbf9de5b2d10c8aaa6ee9241d41e170c.so"
    
    
    file: /home/gitzzly/OpenFOAM/gitzzly-v2012/blastAMR/tutorials/damBreak2D/constant/dynamicMeshDict at line 17 to 91.
    
        From void Foam::codedBase::createLibrary(Foam::dynamicCode&, const Foam::dynamicCodeContext&) const
        in file db/dynamicLibrary/codedBase/codedBase.C at line 201.
    
    FOAM exiting
`

Regards,

**Comment by FoamScience** [comment]
This was cased because `AMRLB_PROJECT` was not set properly. Added a line to all Allrun scripts to set its value as the root folder of the Git repo. Should work now, if it still doesn't work for you, feel free to reopen the issue.
I also added a note to the wiki
Thanks for reporting this!
