### ISSUE TITLE
Compile Problem with WM_LABEL_SIZE=64

### ISSUE THREAD

**Issue by JanGaertner** [STFS-TUDa/blastAMR#2]
Compiling with label size 64 causes an error at: 

```
fvMeshRefiner/fvMeshPolyRefiner/prismatic2DRefinement/prismatic2DRefinement.C:710:5: error: no matching function for call to ‘Foam::syncTools::syncEdgeList(const Foam::polyMesh&, Foam::labelList&, Foam::maxEqOp<long int>, int)’
  709 |     syncTools::syncEdgeList
      |     ~~~~~~~~~~~~~~~~~~~~~~~
  710 |     (
      |     ^
  711 |         mesh_,
      |         ~~~~~~
  712 |         edgeMidPoint,
      |         ~~~~~~~~~~~~~
  713 |         maxEqOp<label>(),
      |         ~~~~~~~~~~~~~~~~~
  714 |         -1
      |         ~~
  715 |     ); 
```

**Comment by JanGaertner** [comment]
After recompiling and setting manually `FOAM_CODE_TEMPLATES` I get now following error

Ctoo: codedErrorEstimatorTemplate.C
In file included from codedErrorEstimatorTemplate.C:29:
codedErrorEstimatorTemplate.H:38:10: fatal error: errorEstimator.H: No such file or directory
   38 | #include "errorEstimator.H"

**Comment by FoamScience** [comment]
> After recompiling and setting manually `FOAM_CODE_TEMPLATES` I get now following error
> 
> Ctoo: codedErrorEstimatorTemplate.C In file included from codedErrorEstimatorTemplate.C:29: codedErrorEstimatorTemplate.H:38:10: fatal error: errorEstimator.H: No such file or directory 38 | #include "errorEstimator.H"

There is another Env. Var. `Allrun` scripts should set to the root of this repository; right here:
https://github.com/STFS-TUDa/blastAMR/blob/69e59eab8c23536af7f0a004759299aaf9ef4a48/src/errorEstimators/codedErrorEstimator/codedErrorEstimator.C#L138

You can check: `your_case/dynamicCode/refinement_name/Make/options` to see if the paths are right for you
If they are not after setting `AMRLB_PROJECT` to repo root, please open a separate issue. 

Make sure you're running the latest commits, check #1
