### ISSUE TITLE
DensityGradient errorEstimator issue

### ISSUE THREAD

**Issue by starflame-Qot** [STFS-TUDa/blastAMR#8]
Hello, I'm back. 😊 Today I'm trying to test out this set of AMR tools that I'm really excited about. 

According to my understanding, I can choose any of the error estimation methods provided to finish my case, only the effect is different. 

My ideal criterion is this density gradient method. However when I use it, it errors at the first step, as shown in the image. 

![Screenshot from 2023-12-22 23-08-58](https://github.com/STFS-TUDa/blastAMR/assets/119994097/3bb246b3-1d25-4e99-91f8-da451c4bf938)

I can use fieldvalue, codes, etc., and here I provide my dict. 

![Screenshot from 2023-12-22 23-09-36](https://github.com/STFS-TUDa/blastAMR/assets/119994097/2a898b53-ab9d-4796-91f1-1bce15bd3781)

Ask for your guidance. This confuses me so much.  

Thank you very much ！

**Comment by FoamScience** [comment]
Hi, not all of the error indicators are well test yet. I exclusively use the `coded` one. Also, it's hard to debug this with the information I have now.

Instead, you can mimic density-gradient-based refinement with the following coded snippet (dimensions of rho might be different for your solver). This example will refine cells whose `rho` gradient falls above 50% of the whole density gradient range. The range is dynamically calculated so you don't have to guess values:
```cpp
errorEstimator  coded;
name            rhoGradient;

code            #{
    Info<< "---->! custom error estimator !<----" << endl;
    error_ = 0.0;
    const auto& rho = mesh_.lookupObject<volScalarField>("rho");
    error_ == mag(fvc::grad(rho)) / dimensionedScalar("one",dimDensity/dimLength,1.0);
    scalar maxGradRho = gMax(error_);
    scalar minGradRho = gMin(error_);

    lowerRefine_ = minGradRho + 0.5*(maxGradRho-minGradRho);
    upperRefine_ =  GREAT;
    lowerUnrefine_ = minGradRho + 0.4*(maxGradT-minGradRho);
    upperUnrefine_ =  GREAT;
    if (scale) normalize(error_);
    Info<< "---->! end    error estimator !<----" << endl;
#};


```

**Comment by starflame-Qot** [comment]
Yes, the method you indicated for the applicable _coded_ is OK. 

We can use the freelyPropFlame2D tutorial as a reference, which should theoretically use the _densitygradient_ criterion, right? 

We can throw the AMR effect first, give priority to ensuring that it runs normally, maybe we can find the potential cause?

**Comment by starflame-Qot** [comment]
One possible source of reason is the calculation of the 2D mesh size. I tested the 2D and 3D damBreak separately in the tutorial study, and the 3D can be calculated, but the 2D will give an error.

**Comment by starflame-Qot** [comment]
Thank you for your guidance. 

Actually my case uses hexahedral cells.

 I will keep trying until I can use it successfully and update here in time.

**Comment by FoamScience** [comment]
I added a more general `gradientRange`  error estimator, which replaces `densityGradient`. Please pull the new commits for your OpenFOAM version.

I think this is a much better solution to this issue since you can choose the target field and a few more settings.

#9 sees a possible optimization opportunity which I may investigate if I find time.

**Comment by FoamScience** [comment]
Closing as not active anymore; using `gradientRange` instead seems to work for all mesh types.
